import Head from 'next/head'
import Community from '../components/Community'
import Footer from '../components/Footer'
import Glimpse from '../components/Glimpse'
import Hero from '../components/Hero'
import Information from '../components/Information'
// import Mission from '../components/Mission'
import RecentNewsletter from '../components/RecentNewsletter'
import RecentPodcast from '../components/RecentPodcast'
// import Subscribe from '../components/Subscribe'
import styles from '../styles/Home.module.css'


const data = {
  title : "Read Newsletters",
}

export default function Home({recent}) {

  console.log(recent)
  return (
      <div className={styles.container}>
        <Head>
          <title>XRAtlas</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/xr.jpeg" />
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
        </Head>

        <main className={styles.main}>
          <Hero />
          <Information />
          <RecentPodcast />
          <Glimpse />
          <RecentNewsletter data={data} recent={recent}/>
          <Community />
          <Footer />
        </main>
      </div>
  )
}

// export async function getStaticProps(){
//   try {
//       const fetchingData = await axios.get("http://xr-speeds-production.up.railway.app/recent")
//       const response = fetchingData.data;
//       // console.log(response)
//       return { 
//           props : { recent : response }
//        }
//   } catch (error) {
//       console.log(error)
//   }
// }